server:
  port: 80
eureka:
  client:
#    register-with-eureka: false 集群
    register-with-eureka: true #单机
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #单机版
#      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
spring:
  application:
    name: cloud-openfeign-consumer-order
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      minimum-idle: 10
      maximum-pool-size: 25
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.imugen.springcloud.PaymentFeignService: debug